aliyun-oss:
    endpoint: ""
    access-key-id: ""
    access-key-secret: ""
    bucket-name: ""
    bucket-url: ""
    base-path: ""
autocode:
    web: web/src
    root: C:\Users\11620\Desktop\Code\Git\Golang\gin-vue-admin
    server: server
    module: github.com/flipped-aurora/gin-vue-admin/server
    ai-path: ""
aws-s3:
    bucket: ""
    region: ""
    endpoint: ""
    secret-id: ""
    secret-key: ""
    base-url: ""
    path-prefix: ""
    s3-force-path-style: false
    disable-ssl: false
captcha:
    key-long: 6
    img-width: 240
    img-height: 80
    open-captcha: 0
    open-captcha-timeout: 3600
cloudflare-r2:
    bucket: ""
    base-url: ""
    path: ""
    account-id: ""
    access-key-id: ""
    secret-access-key: ""
cors:
    mode: strict-whitelist
    whitelist:
        - allow-origin: example1.com
          allow-methods: POST, GET
          allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
        - allow-origin: example2.com
          allow-methods: GET, POST
          allow-headers: content-type
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
db-list:
    - type: ""
      alias-name: ""
      prefix: ""
      port: ""
      config: ""
      db-name: ""
      username: ""
      password: ""
      path: ""
      engine: ""
      log-mode: ""
      max-idle-conns: 10
      max-open-conns: 100
      singular: false
      log-zap: false
      disable: true
disk-list:
    - mount-point: /
email:
    to: ""
    from: ""
    host: ""
    secret: ""
    nickname: ""
    port: 0
    is-ssl: false
    is-loginauth: false
excel:
    dir: ./resource/excel/
hua-wei-obs:
    path: ""
    bucket: ""
    endpoint: ""
    access-key: ""
    secret-key: ""
jwt:
    signing-key: 04b8a183-def3-4554-ba92-b8af554b45af
    expires-time: 7d
    buffer-time: 1d
    issuer: qmPlus
local:
    path: uploads/file
    store-path: uploads/file
mcp:
    name: ""
    version: ""
    sse_path: ""
    message_path: ""
    url_prefix: ""
    addr: 0
    separate: false
minio:
    endpoint: ""
    access-key-id: ""
    access-key-secret: ""
    bucket-name: ""
    use-ssl: false
    base-path: ""
    bucket-url: ""
mongo:
    coll: ""
    options: ""
    database: ""
    username: ""
    password: ""
    auth-source: ""
    min-pool-size: 0
    max-pool-size: 0
    socket-timeout-ms: 0
    connect-timeout-ms: 0
    is-zap: false
    hosts: []
mssql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 0
    max-open-conns: 0
    singular: false
    log-zap: false
mysql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 0
    max-open-conns: 0
    singular: false
    log-zap: false
oracle:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 0
    max-open-conns: 0
    singular: false
    log-zap: false
pgsql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 0
    max-open-conns: 0
    singular: false
    log-zap: false
qiniu:
    zone: ""
    bucket: ""
    img-path: ""
    access-key: ""
    secret-key: ""
    use-https: false
    use-cdn-domains: false
redis:
    name: ""
    addr: ""
    password: ""
    db: 0
    useCluster: false
    clusterAddrs: []
redis-list: []
sqlite:
    prefix: ""
    port: ""
    config: ""
    db-name:
    username: ""
    password: ""
    path: C:\Users\11620\Desktop\Code\Git\Golang\gin-vue-admin\server
    engine: ""
    log-mode: error
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
system:
    db-type: sqlite
    oss-type: local
    router-prefix: ""
    addr: 8888
    iplimit-count: 15000
    iplimit-time: 3600
    use-multipoint: false
    use-redis: false
    use-mongo: false
    use-strict-auth: false
    disable-auto-migrate: false
tencent-cos:
    bucket: ""
    region: ""
    secret-id: ""
    secret-key: ""
    base-url: ""
    path-prefix: ""
zap:
    level: info
    prefix: '[jy-code]'
    format: console
    director: log
    encode-level: LowercaseColorLevelEncoder
    stacktrace-key: stacktrace
    show-line: true
    log-in-console: true
    retention-day: -1
